# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3.5.2
      -
        uses: rlespinasse/github-slug-action@v4
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      -
        name: yarn install
        run: yarn install
      -
        name: Build
        run: yarn run build
      -
        name: Adjust version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version --no-git-tag-version ${{ env.GITHUB_REF_SLUG }}
      -
        name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}