# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3.5.2
      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      -
        name: yarn install
        run: yarn install
      -
        name: Build
        run: yarn run build
      -
        name: Adjust version
        run: npm version ${{ env.GITHUB_REF_SLUG }}
      -
        name: Publish
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}